site_name: SERVICIOS EN RED
site_url: https://JoseAngelSeveroOchoa.github.io/Servicios-en-red/

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
  language: es

nav:
  - Inicio: index.md
  - Unidades:
    - UD01_DHCP: UD01_DHCP.md
  - Prácticas:
    - UD01_DHCP_PRACTICA1: UD01_DHCP_PRACTICA1.md
 

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - tables                 # necesario para las tablas Sintaxis/Ejemplo
  - pymdownx.highlight      # resaltado de sintaxis en los bloques ```
  - pymdownx.inlinehilite    # resaltado en código inline (`dhcpd.conf`, etc.)
  - pymdownx.tasklist:
      custom_checkbox: true # checklists visuales (- [ ] ...)
  - toc:
      permalink: true       # opcional, añade anclas a los títulos (## 4.1 Declaraciones)